<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bpmn" nsURI="http://bpmn/1.0" nsPrefix="bpmn">
  <eClassifiers xsi:type="ecore:EClass" name="ProcessModel" eSuperTypes="#//BPMNObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pools" upperBound="-1"
        eType="#//Pool" containment="true" eOpposite="#//Pool/processModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessObject" abstract="true" eSuperTypes="#//BPMNObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pool" lowerBound="1" eType="#//Pool"
        eOpposite="#//Pool/processObjects"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowObject" abstract="true" eSuperTypes="#//ProcessObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pool" eSuperTypes="#//BPMNObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="processObjects" upperBound="-1"
        eType="#//ProcessObject" containment="true" eOpposite="#//ProcessObject/pool"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processModel" lowerBound="1"
        eType="#//ProcessModel" eOpposite="#//ProcessModel/pools"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true" eSuperTypes="#//FlowObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="StartEvent" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="EndEvent" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntermediateEvent" eSuperTypes="#//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" abstract="true" eSuperTypes="#//FlowObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//Activity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Gateway" abstract="true" eSuperTypes="#//FlowObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Exclusive" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parallel" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="Connection" abstract="true" eSuperTypes="#//ProcessObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ProcessObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ProcessObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceFlow" eSuperTypes="#//Connection"/>
  <eClassifiers xsi:type="ecore:EClass" name="Artifact" abstract="true" eSuperTypes="#//ProcessObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataObject" eSuperTypes="#//Artifact"/>
  <eClassifiers xsi:type="ecore:EClass" name="MessageFlow" eSuperTypes="#//Connection"/>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="#//Connection"/>
  <eClassifiers xsi:type="ecore:EClass" name="BPMNObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subprocess" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="processObjects" upperBound="-1"
        eType="#//ProcessObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collapsed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Group" eSuperTypes="#//Artifact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="processObjects" upperBound="-1"
        eType="#//ProcessObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annotation" eSuperTypes="#//Artifact"/>
  <eClassifiers xsi:type="ecore:EClass" name="Complex" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inclusive" eSuperTypes="#//Gateway"/>
</ecore:EPackage>
